AMReX-FHD/FHDeX

exec/immersedIons/inputs_regression_cond
exec/immersedIons/main_driver.cpp
exec/immersed_boundary/channel_dumbbell/advance.cpp
exec/immersed_boundary/channel_multiblob/advance.cpp
exec/immersed_boundary/channel_multiblob/main_driver.cpp
exec/immersed_boundary/flagellum/ib_md.cpp
src_immersed-boundary/IBMarkerContainer.H
src_immersed-boundary/IBMarkerContainer.cpp
src_immersed-boundary/IBMarkerContainerBase.H
src_immersed-boundary/IBMarkerContainerBaseI.H
src_immersed-boundary/IBMultiBlobContainer.H
src_immersed-boundary/IBMultiBlobContainer.cpp
src_immersed-boundary/IBParticleContainer.H
src_immersed-boundary/IBParticleContainer.cpp
src_particles/FhdParticleContainer.cpp

These are a few changes that were needed before we can port the particle code in FHDeX to C++ / GPUs. 
I tested this using the deterministic version of the immersedIons test that runs every night. These are diffs I get:
variable name      |      absolute error      |      relative error
------------ | ------------- | --------------
averaged_velx         |             6.938893904e-17      |     4.120906547e-16
averaged_vely         |             9.714451465e-17     |      6.675664696e-16
averaged_velz         |            5.551115123e-17      |     4.944677048e-16
shifted_velx             |          7.632783294e-17       |    4.513945216e-16
shifted_vely             |          1.110223025e-16       |    7.251131321e-16
shifted_velz             |          6.938893904e-17      | …

Update neighbor particle stuff to use the new C++-ready style.

---

src_compressible/boundary.cpp
src_compressible/compressible_functions.H
src_compressible/timeStep.cpp

Added logic to set species and total mass flux to be zero at the walls for an an isothermal walls. This is required to negate the Soret effects at the walls.

Set correct BC for isothermal walls

---

src_common/common_functions.H
src_common/common_functions.cpp
src_common/common_namespace.H
src_common/src_F90/common_namelist.F90
src_compressible/compressible_functions.H
src_compressible_stag/compressible_functions_stag.H
src_multispec/ElectroDiffusiveMassFluxdiv.cpp
src_multispec/multispec_functions.H
src_multispec/src_F90/multispec_namelist.F90

Make max_species consistent in namespace and namelist
Remove LOHI since it's hardly used and equal to 2
Move max_element into common namespace and namelist

Fix max species

---

src_compressible_stag/boundaryStag.cpp
src_compressible_stag/fluxStag.cpp

This PR changes how Dirichlet boundaries are handled in the staggered compressible code. The ghost cells now carry the Dirichlet boundaries values rather than a linear extrapolation. This will make the boundary implementation more accurate, and also prevent unphysical values in the ghost cells arising from extrapolation (such as negative temperature and mass fractions).

Dirichlet BC for compressible staggered code

---

.github/workflows/dependencies/dependencies_nvcc11.sh

Update key fetching in the dependencies script for the workflow. Also includes changes to install only specific cuda packages instead of the full suite. Finally, the cuda check will use Cuda ver. 11.2.

Ci key fix

---

.github/workflows/dependencies/dependencies_nvcc11.sh

This downloads only specific CUDA modules instead of the whole toolkit. This results in a few mins faster CI run.

CI: Download only needed CUDA modules

---

exec/hydro/advance.cpp
exec/immersed_boundary/channel_dumbbell/advance.cpp
exec/immersed_boundary/channel_dumbbell/main_driver.cpp
exec/immersed_boundary/channel_multiblob/advance.cpp
exec/immersed_boundary/channel_multiblob/main_driver.cpp
exec/immersed_boundary/channel_rigid/advance.cpp
exec/immersed_boundary/channel_rigid/main_driver.cpp
exec/immersed_boundary/flagellum/advance_CN.cpp
exec/immersed_boundary/flagellum/advance_midpoint.cpp
exec/immersed_boundary/flagellum/advance_stokes.cpp
exec/immersed_boundary/flagellum/main_driver.cpp
exec/lib_hydro/demo/main_driver.cpp
exec/multispec/AdvanceTimestepBousq.cpp
exec/multispec/AdvanceTimestepInertial.cpp
exec/multispec/main_driver.cpp
src_common/MultiFabPhysBC.cpp
src_common/common_functions.H
src_common/common_functions.cpp
src_gmres/ApplyMatrix.cpp
src_gmres/GMRES.cpp
src_gmres/gmres_functions.H
src_hydro/AddMFluctuations.cpp
src_hydro/MacProj_hydro.cpp
src_hydro/advance.cpp
src_multispec/InitialProjection.cpp

Fix moving wall implementation - need to split MultiFabPhysBC into homogeneous and inhomogeneous versions, and call the inhomogeneous version at all times until the GMRES solver starts.

Wallspeed fix

---

exec/compressible_stag_mui/SPPARKS_MUI/app_surfchemtest.cpp
exec/compressible_stag_mui/SPPARKS_MUI/app_surfchemtest.h

The domain decomposition on the KMC side might split an FHD cell between two
different MPI processes.  This commit fixes a bug that did not take this
into account.

Fix a bug when using amrex::MPMD

---

exec/multispec/AdvanceTimestepBousq.cpp
exec/multispec/AdvanceTimestepInertial.cpp
exec/multispec/inputs_2_bubbles_3d
src_hydro/BDS.cpp
src_hydro/hydro_functions.H

Ensure that the BDS edge states satisfy the constraint.
Boussinesq variant coded up; inertial will come later when someone tries to invoke it (with an error and fortran code to be converted).

Add BDS Edge State Projection

---

exec/multispec/GNUmakefile
src_common/common_namespace.H
src_multispec/multispec_functions.cpp

Now define MAX_ELEMENT as a compile-time parameter instead of hard-coded.
Must be equal to MAX_SPECIES*(MAX_SPECIES-1)/2 or it will abort.
Default value is 28

Max element

---

src_compressible/compressible_functions.cpp
src_compressible/compressible_namespace.H
src_compressible/transCoeffs.cpp
src_compressible_stag/compressible_functions_stag.H
src_compressible_stag/main_driver.cpp
src_compressible_stag/writePlotFileStag.cpp

This PR adds support to specify the bulk viscosity contribution to the stress tensor (both stochastic and diffusive). This is enabled by specifying `visc_type = 3` and then defining a `zeta_ratio`, which sets the bulk viscsoity `zeta = zeta_ratio*eta`, where eta is the shear viscosity. This is done on a cell-by-cell basis.

Added support for bulk viscosity in staggered compressible FHD

---

src_compressible_stag/fluxStag.cpp

Thanks to Changho for spotting both of these.
Fixed a bug in the z ChiX stencil.
Fixed an error in the z heat flux indexing which doesn't ultimately affect the simulation since it's summed into the same location in memory in the end anyway regression tests will likely change when this is merged.

Flux Index Bugs

---

exec/hydro/main_driver.cpp
src_analysis/StructFact.H
src_analysis/StructFact.cpp

Enable restart of structure factor class.
Does not work on the decomposed dilational/solenoidal (yet).

Structure factor restart

---

exec/chemistry_testing/main.cpp
src_chemistry/chemistry_functions.cpp
src_common/common_functions.cpp
src_common/common_namespace.H
src_compressible/compressible_functions.cpp
src_compressible/main_driver.cpp
src_compressible_stag/reservoirStag.cpp

address a long-standing issue where sometimes its preferable to specify the avogadro number instead of Runiv.
If avogadro is supplied, then Runiv is set to avogadro * k_b
Default behavior is preserved as all codes presently set Runiv
The code will abort if you try to specify both.

Avogadro Number

---

exec/compressible_stag/test_MFsurfchem_COAr_eq/inputs_fhd_stag
exec/compressible_stag/test_MFsurfchem_COAr_eq/params_COAr_eq.py
src_MFsurfchem/MFsurfchem_functions.cpp

PR to review the revised scheme for MFsurfchem. (original) number density  to (revised) pressure
1. src_MFsurfchem
- Default value of k_beta = -1/2
- Variable "dens" = partial pressure
2. test_MFsurfchem_COAr_eq
- ads_rate_const in "inputs_fhd_stag" and kads1 in "params_COAr_eq.py"

MFsurfchem - change number density to pressure

---

src_common/ComputeAverages.cpp
src_compressible_stag/main_driver.cpp

Implement slice structure factor for compressible_stag
To use, set project_dir (normal direction of plane) and slicepoint (coordinate in project_dir to slice) in the inputs file; e.g. if you care about the k=0 plane use project_dir=2 and slicepoint=0
If you do not specify slicepoint it will take the vertical average over project_dir over the entire dataset
plt_SF_prim_Flattened plt_SF_cons_Flattened contains the result

Implement slice structure factor for compressible_stag

---

exec/compressible/inputs_giantfluct_3d
src_compressible_stag/boundaryStag.cpp

fix inputs_giantflux_3d to work by ensuring bc YK's sum to 1
add error checking for this condition in the compressible_stag code
This example only runs in the compressible_stag framework at present.  The cell-centered run aborts since the n_cells_z=1 case for stoch flux is not supported yet.

Fix inputs_giantfluct_3d to work by ensuring bc YK's sum to 1

---

src_common/ComputeAverages.cpp
src_common/common_functions.H
src_common/common_functions.cpp
src_common/common_namespace.H
src_compressible_stag/writePlotFileStag.cpp

add ability to write deltaY = (Yinstant - Ybar) to plotfile in compressible_stag.
Ybar is the horizontal average in the plot_deltaY_dir direction.
Must specify in inputs file:
plot_deltaY_dir = (0, 1, or 2; default value is -1 "off")

add ability to write deltaY to plotfile in compressible_stag

---

exec/compressible_mui/sav_src/2020/m00.cpp
exec/compressible_mui/sav_src/2020/m01-cutemp_jsq.cpp
exec/compressible_mui/sav_src/2020/m01.cpp
exec/compressible_mui/sav_src/2020/m02.cpp
exec/compressible_mui/sav_src/2020/m10.cpp
exec/compressible_mui/sav_src/2020/m11.cpp
exec/compressible_mui/sav_src/2020/m12.cpp
exec/compressible_mui/sav_src/202101_before_mui_span/main_driver.cpp
exec/compressible_mui/sav_src/202101_before_mui_span/main_driver.cpp_0126_bc
exec/compressible_mui/sav_src/202106_before_summer/main_driver.cpp
exec/hydro/main_driver.cpp
src_common/ComputeAverages.cpp
src_common/common_functions.H
src_compressible/main_driver.cpp
src_compressible_stag/main_driver.cpp
unmaintained/exercises/compressible/main_driver.cpp

cleanup ExtractSlice and ComputeVerticalAverage routines
fix index bug for case where ComputeVerticalAverage is called with incomp>0
fixes the issue with running ComputeVerticalAverage on the GPU - you will no longer need to use amrex.the_arena_is_managed=1

Average cleanup

---

exec/DSMC/main_driver.cpp
exec/DSMC_granular/main_driver.cpp
exec/cellbdytest_new/main_driver.cpp
exec/hydro/main_driver.cpp
exec/immersedIons/main_driver.cpp
exec/multispec/main_driver.cpp
exec/structFactTest/main_driver.cpp
src_MFsurfchem/MFsurfchem_functions.cpp
src_analysis/StructFact.H
src_analysis/StructFact.cpp
src_compressible/main_driver.cpp
src_compressible_stag/main_driver.cpp
src_reactDiff/main_driver.cpp

-Cleanup logic for when structure factors are permitted and computed based on do_1D, do_2D, project_dir, do_slab_sf.
--This fixes the struct_fact_int>0 and (do_2D=1) case Changho reports.
-Prevent surfCov structure factor from being computed with nx=ny=1
--This fixes the nx=ny=1 and meansurfchem=on case Changho reports.
-Structure factors now report k space index in the plotfile when you query the "physical" location.
--The structure factor data itself is not modified; this only affects the "prob_lo" and "prob_hi" of the plotfile.  This is a cosmetic fix only as it allows users using amrVis to easily see kx,ky,kz for a given cell in a SF plotfile.
Ffor uncoupled z-plane case (do_2D=1) the output structure factor is the average over each plane's individual structure factor.  There is no SF …

Structure Factor Fixes

---

src_MFsurfchem/MFsurfchem_functions.H
src_MFsurfchem/MFsurfchem_functions.cpp
src_MFsurfchem/MFsurfchem_namespace.H
src_compressible_stag/main_driver.cpp

PR to review the "conversion_MFsurfchem" - modify the species involved in the desorption species.
1. conversion_MFsurfchem (default = 0, adsorption and desorption of species 1)
adsorption of species 1 and desorption of species (1+conversion_MFsurfchem)
2. dNads, dNdes (src_compressible_stag/main_driver.cpp)
To compute the number of adsorption and desorption separately.
(dNadsdes is defined as the difference between number of adsorption and desorption processes.)

MFsurfchem - modification of desorption species

---

src_compressible_stag/Checkpoint.cpp
src_compressible_stag/compressible_functions_stag.H
src_compressible_stag/main_driver.cpp

It now runs but there is still an issue with the seed restart.

do_2D mode with surface coverage restart fixes.

---

src_compressible_stag/main_driver.cpp

Now when using surface chemistry and do_2D, the surface chemistry structure factor is no longer a plane, but the average of many pencils.
Note there is now the strict requirement when n_ads_spec>0 and do_2D=1 that 
-project_dir=2 (so each z plane is decoupled) and
-ads_wall_dir=1 (surface chemistry is the lo-y wall).
Thus, the surfaceCoverage structure factor is the average of many 1D x-pencils of surface coverage.

Support for ensemble of pencil structure factor multifabs for the surface chemistry in do_2D mode

---

exec/compressible_stag_mui/GNUmakefile
src_MFsurfchem/MFsurfchem_functions.cpp
src_compressible_stag/main_driver.cpp

1. src_compressible_stag/main_driver.cpp
: At line 138, the error message appears even when do_1D = 1. I suggest adding "&& do_1D == 0".
2. src_MFsurfchem/MFsurfchem_functions.cpp
: Fix dx[#] in the calculation of Ntot, based on the surface direction (ads_wall_dir).
Note that there was no issue with the previous result because I used dx=dy=dz before.
3. exec/compressible_stag_mui/GNUmakefile
: Based on the change in exec/compressible_stag/GNUmakefile, I have fixed GNUmakefile in compressible_stag_mui. I believe there are no issues.

Small fixes - main_driver.cpp and MFsurfchem

---

src_compressible_stag/main_driver.cpp

I forgot to initialize a temporary multifab, and also forgot to initialize the multifab storing the pencil sum to zero (it was uninitialized)

Fix errors in do_2D mode surface coverage structure factor

---

src_compressible_stag/main_driver.cpp

When using do_2D, you can now specify slicepoint = (a number that is not -1) to take an average of the pencil structure factors in the y direction (since we force ads_wall_dir=1 for do_2d mode).
Example useage to obtain the average of all pencil structure factors adjacent to the surface at the low-y interface
n_ads_spec = 1
do_2D = 1
project_dir = 2 // required to be 2 if do_2D=1, or else will abort
ads_wall_dir = 1 // required to be 1 if do_2D=1 and n_ads_spec>0, or else will abort
slicepoint = 0 // get the average of all the structure pencil factors at j=0

do_2d mode slice structure factor

---

src_compressible/transCoeffs.cpp

When computing cell-centered transport coefficients, include only 1 ghost cell.
-The second layer of ghost cells don't affect the solution
-This fixes the do_1D "X by 1 by 1" case for an actual 1D pencil - the second ghost cell is never filled with a FillBoundary.

1 ghost cell for computing transport coefficients

---

src_MFsurfchem/MFsurfchem_functions.cpp
src_MFsurfchem/MFsurfchem_namespace.H
src_compressible_stag/main_driver.cpp

1. src_compressible_stag/main_driver.cpp
: There is an error when simulating 3D system with both SF calculation and n_ads_spec>0.
This error is resolved by adding "do_2D &&" at line 1655 (if condition for plt_SF_surfcov_2D).
I fixed it temporarily since (i) it works in my current systems, and (ii) the error only occurs when n_ads_spec>0.
2. src_MFsurfchem/MFsurfchem_functions.cpp and MFsurfchem_namespace.H
: add mean_MFsurfchem and mean_pressure[m], to compute adsorption and desorption rates with equilibrium values

Small fix in SF_surfcov_2D plot and mean_MFsurfchem
