src_gmres/ApplyPrecon.cpp, src_gmres/GMRES.cpp, src_gmres/Make.package, src_gmres/StagMGSolver.H, src_gmres/StagMGSolver.cpp, src_gmres/gmres_functions.H
StagMG solver is now in a class to reduce re-allocation of temporary multifabs
=> Stag mg solver class

exec/compressible/main_driver.cpp, exec/exercises/compressible/main_driver.cpp, src_compressible/compressible_functions.H, src_compressible/compressible_functions_F.H, src_compressible/conservedPrimitiveConversions.cpp, src_compressible/src_F90/conv_funcs.F90, src_rng/MultiFabFillRandom.cpp
=> Put cons_to_prim on GPU

exec/immersedIons/main_driver.cpp
Adding into main_driver the same C++ rng engine initialization as Checkpoint
=> implement seed=0 for C++ rng engine

exec/compressible/main_driver.cpp, src_compressible/boundary.cpp, src_compressible/compressible_functions.cpp, src_compressible/flux.cpp, src_compressible/timeStep.cpp
This PR fixes boundary conditions for energy flux -- particularly the Dufour and viscous heating components at concentration and slip/no-slip walls. Similar fixes for compressible staggered to follow.
=> Fix bc compressible

src_multispec/multispec_functions.H
Pulled over comments from the Fortran file and added my own.
=> added comments, fixed spelling

src_particles/DsmcParticleContainer.cpp
Update DsmcParticle Containers for GPU stuff
=> Debug main

exec/compressible/main_driver.cpp, src_chemistry/chemistry_functions.H, src_chemistry/chemistry_functions.cpp, src_compressible/compressible_functions.H, src_compressible/timeStep.cpp
Merging compressible_CLE_RK3 to main branch
=> compressible_CLE_RK3: compute_chemistry_source_CLE_RK3

exec/DSMC_granular/input_test, exec/DSMC_granular/main_driver.cpp, src_common/common_functions.cpp, src_common/common_functions_F.H, src_common/common_namespace.H, src_common/common_namespace_declarations.H, src_common/src_F90/common_namelist.F90, src_geometry/paramPlane.cpp, src_particles/DsmcParticleContainer.cpp
Fixed concentration boundaries
- Accepts both mass and number densities at boundaries
- Tested for two identical species
=> Merge granular

exec/compressible/main_driver.cpp, exec/compressible_mui/main_driver.cpp, exec/compressible_stag/main_driver.cpp, src_compressible/compressible_functions.H, src_compressible/compressible_functions.cpp, src_compressible_stag/compressible_functions_stag.H, src_compressible_stag/compressible_functions_stag.cpp
initialize only the conserved, then call consToPrim
=> clean up how variables are initialized

src_common/ComputeDivAndGrad.cpp, src_common/common_functions.H, src_hydro/MkAdvMFluxdiv.cpp, src_hydro/MkAdvSFluxdiv.cpp, src_hydro/StochMomFlux.cpp, src_multispec/ElectroDiffusiveMassFluxdiv.cpp
all of the "increment" branching statements have been combined
this affects many routines and eliminates a lot of of redudant code.
for example, ComputeGrad:
if (increment == 0)
zero the output
then increment the output
grad += ...
=> Cleanup Increment Options

exec/hydro/advance.cpp, exec/hydro/inputs_shearwall_2d, exec/hydro/inputs_shearwall_3d, src_common/MultiFabPhysBC.cpp, src_common/common_functions.cpp, src_common/common_namespace.H, src_gmres/GMRES.H, src_gmres/GMRES.cpp
=> Shear wall

exec/compressible_stag/test_MFsurfchem_RB/inputs_fhd_stag, src_MFsurfchem/MFsurfchem_functions.cpp, src_MFsurfchem/MFsurfchem_namespace.H
Pull request to merge MFsurfchem branch into main branch
=> MFsurfchem

exec/compressible_stag_mui/SPPARKS_MUI/app_surfchemtest.cpp, exec/compressible_stag_mui/SPPARKS_MUI/app_surfchemtest.h
=> New branch first commit

exec/compressible_stag_mui/SPPARKS_MUI/app_surfchemtest.cpp, exec/compressible_stag_mui/SPPARKS_MUI/app_surfchemtest.h, exec/compressible_stag_mui/SPPARKS_MUI/diag_surfchemtest.cpp, exec/compressible_stag_mui/test_COO2CO2Ar_reaction_slurm/ads.py, exec/compressible_stag_mui/test_COO2CO2Ar_reaction_slurm/ads.sh, exec/compressible_stag_mui/test_COO2CO2Ar_reaction_slurm/amrex_job_script.sh, exec/compressible_stag_mui/test_COO2CO2Ar_reaction_slurm/amrex_mpmd.conf, exec/compressible_stag_mui/test_COO2CO2Ar_reaction_slurm/clean.sh, exec/compressible_stag_mui/test_COO2CO2Ar_reaction_slurm/create_site_file.py, exec/compressible_stag_mui/test_COO2CO2Ar_reaction_slurm/event_rate_FHD.py, exec/compressible_stag_mui/test_COO2CO2Ar_reaction_slurm/in.kmc_amrex, exec/compressible_stag_mui/test_COO2CO2Ar_reaction_slurm/inputs_fhd_stag, exec/compressible_stag_mui/test_COO2CO2Ar_reaction_slurm/submit_job.sh, src_surfchem_amrex/surfchem_mui_functions.cpp
Update nspec_mui = 3 code (FHD) and reaction, diag (KMC)
Upload nspec_mui = 3 test case
=> Surfchemtest

exec/compressible_stag/test_NO2_dimerization_eq/README, exec/compressible_stag/test_NO2_dimerization_eq/clean.sh, exec/compressible_stag/test_NO2_dimerization_eq/diff.sh, exec/compressible_stag/test_NO2_dimerization_eq/inputs_NO2_dimerization_eq, exec/compressible_stag/test_NO2_dimerization_eq/job_script.sh, exec/compressible_stag/test_NO2_dimerization_eq/params_NO2_N2O4_thermochem.py, exec/compressible_stag/test_NO2_dimerization_eq/params_NO2_dimerization_eq.py, exec/compressible_stag/test_NO2_dimerization_eq/submit_job.sh, exec/compressible_stag/test_NO2_dimerization_neq/README, exec/compressible_stag/test_NO2_dimerization_neq/avg.sh, exec/compressible_stag/test_NO2_dimerization_neq/clean.sh, exec/compressible_stag/test_NO2_dimerization_neq/diff.sh, exec/compressible_stag/test_NO2_dimerization_neq/inputs_NO2_dimerization_neq, exec/compressible_stag/test_NO2_dimerization_neq/job_script.sh, exec/compressible_stag/test_NO2_dimerization_neq/params_NO2_dimerization_rate_const.py, exec/compressible_stag/test_NO2_dimerization_neq/submit_job.sh, src_compressible_stag/compressible_functions_stag.H, src_compressible_stag/main_driver.cpp, src_compressible_stag/timeStepStag.cpp
PR to add the relevant reactive stochastic chemistry routines into the staggered code framework
=> FHDeX/src_compressible_stag: adding chemistry source

exec/multispec/AdvanceTimestepBousq.cpp
Implemented BDS Advection (advection_type=1 (unlimited) and 2 (limited)) for the Boussinesq integrator in multispecies (algorithm_type=6)
=> BDS Advection for Boussinesq

src_gmres/StagApplyOp.cpp, src_gmres/StagMGSolver.cpp
fix managed memory issue in staggered multigrid solver
=> fix managed memory

exec/chemistry_testing/chemistry_testing_functions.H, exec/chemistry_testing/chemistry_testing_functions.cpp, src_chemistry/chemistry_functions.H, src_chemistry/chemistry_functions.cpp, src_compressible/timeStep.cpp, src_compressible_stag/timeStepStag.cpp
prep code for rewrite of new chemistry routines for the low Mach and reactDiff codes
=> Prep Chemistry for new LM and reactDiff routines

src_reactDiff/AdvanceDiffusion.cpp, src_reactDiff/AdvanceReactionDiffusion.cpp, src_reactDiff/InitN.cpp, src_reactDiff/Make.package, src_reactDiff/MultinomialDiffusion.cpp, src_reactDiff/reactDiff_functions.H
Implemented multinomial diffusion options (CPU only, doesn't work for GPU)
=> Multinomial

src_compressible_stag/main_driver.cpp
enable in the inputs files with n_ads_spec > 0 using:
struct_fact_int = 1
n_steps_skip = <desired amount>
structure factor plotfiles are written out at plot_int interval
=> surface chemistry structure factor
